-- SQL PARA ACTUALIZAR LA BASE DE DATOS EXISTENTE
-- Copia y corre esto en el SQL Editor de Supabase

-- 1. Agregar campos de verificación solo si no existen
DO $$ 
BEGIN 
    -- Tipo de documento
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tecnicos' AND column_name='tipo_documento') THEN
        ALTER TABLE tecnicos ADD COLUMN tipo_documento VARCHAR(20) DEFAULT 'CC';
    END IF;

    -- Número de documento
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tecnicos' AND column_name='numero_documento') THEN
        ALTER TABLE tecnicos ADD COLUMN numero_documento VARCHAR(50);
    END IF;

    -- Foto Perfil
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tecnicos' AND column_name='foto_perfil_url') THEN
        ALTER TABLE tecnicos ADD COLUMN foto_perfil_url TEXT;
    END IF;

    -- Foto Documento
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tecnicos' AND column_name='foto_documento_url') THEN
        ALTER TABLE tecnicos ADD COLUMN foto_documento_url TEXT;
    END IF;

    -- Estado Verificación
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tecnicos' AND column_name='estado_verificacion') THEN
        ALTER TABLE tecnicos ADD COLUMN estado_verificacion VARCHAR(20) DEFAULT 'pendiente';
    END IF;

    -- Fecha Verificación
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tecnicos' AND column_name='fecha_verificacion') THEN
        ALTER TABLE tecnicos ADD COLUMN fecha_verificacion TIMESTAMP;
    END IF;

    -- Nota Verificación
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tecnicos' AND column_name='nota_verificacion') THEN
        ALTER TABLE tecnicos ADD COLUMN nota_verificacion TEXT;
    END IF;
END $$;

-- 2. Crear índices (estos no fallan si ya existen con IF NOT EXISTS)
CREATE INDEX IF NOT EXISTS idx_tecnicos_estado_verificacion ON tecnicos(estado_verificacion);
CREATE INDEX IF NOT EXISTS idx_tecnicos_numero_documento ON tecnicos(numero_documento);

-- 3. Actualizar restricciones
ALTER TABLE tecnicos DROP CONSTRAINT IF EXISTS check_estado_verificacion;
ALTER TABLE tecnicos ADD CONSTRAINT check_estado_verificacion CHECK (estado_verificacion IN ('pendiente', 'verificado', 'rechazado'));

ALTER TABLE tecnicos DROP CONSTRAINT IF EXISTS check_tipo_documento;
ALTER TABLE tecnicos ADD CONSTRAINT check_tipo_documento CHECK (tipo_documento IN ('CC', 'CE', 'TI', 'Pasaporte'));

-- 4. Crear tabla de especialidades si no existe
CREATE TABLE IF NOT EXISTS especialidades_tecnico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tecnico_id uuid REFERENCES tecnicos(id) ON DELETE CASCADE,
    tipo_electrodomestico text NOT NULL,
    marca text,
    es_autorizado boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
